Document: libcamera
Title: Debian libcamera Manual
Author: <insert document author here>
Abstract: This manual describes what libcamera is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcamera/libcamera.sgml.gz

Format: postscript
Files: /usr/share/doc/libcamera/libcamera.ps.gz

Format: text
Files: /usr/share/doc/libcamera/libcamera.text.gz

Format: HTML
Index: /usr/share/doc/libcamera/html/index.html
Files: /usr/share/doc/libcamera/html/*.html
